// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK_dno8VFvAYfBsJdKxvJl_2-9rmYAM8Y',
    appId: '1:690492811226:web:e889f0fd5f14069e1ac2e3',
    messagingSenderId: '690492811226',
    projectId: 'learning-b-4088d',
    authDomain: 'learning-b-4088d.firebaseapp.com',
    storageBucket: 'learning-b-4088d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGaPcc_X6AEojxQI4pOjkc4Za-roU6kA8',
    appId: '1:690492811226:android:72ab566677761c101ac2e3',
    messagingSenderId: '690492811226',
    projectId: 'learning-b-4088d',
    storageBucket: 'learning-b-4088d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDPse8aos-Asudm-XEadUiOFmVw8KxR0k',
    appId: '1:690492811226:ios:13d2a7c544aa11351ac2e3',
    messagingSenderId: '690492811226',
    projectId: 'learning-b-4088d',
    storageBucket: 'learning-b-4088d.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDPse8aos-Asudm-XEadUiOFmVw8KxR0k',
    appId: '1:690492811226:ios:13d2a7c544aa11351ac2e3',
    messagingSenderId: '690492811226',
    projectId: 'learning-b-4088d',
    storageBucket: 'learning-b-4088d.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK_dno8VFvAYfBsJdKxvJl_2-9rmYAM8Y',
    appId: '1:690492811226:web:7d859c7215bc065f1ac2e3',
    messagingSenderId: '690492811226',
    projectId: 'learning-b-4088d',
    authDomain: 'learning-b-4088d.firebaseapp.com',
    storageBucket: 'learning-b-4088d.appspot.com',
  );
}
